services:
  # --- Serviço Backend (Django) ---
  backend:
    build: ./backend
    container_name: arasaka-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  # --- Serviço Frontend (Next.js) ---
  frontend:
    build: ./frontend
    container_name: arasaka-frontend
    # CORREÇÃO AQUI: Removemos o 'd' extra do final
    command: npx next dev --webpack
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  # --- Serviço Banco de Dados (Postgres) ---
  db:
    image: postgres:15-alpine
    container_name: arasaka-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data: