# Generated by Django 6.0 on 2026-05-01 05:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0007_chapter_translated_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('api', 'API'), ('scraper', 'Scraper'), ('hybrid', 'Híbrido')], default='scraper', max_length=16)),
                ('base_url', models.URLField(max_length=300)),
                ('languages', models.JSONField(default=list, help_text="Lista de códigos de idioma, ex: ['pt-br', 'en']")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(default=100, help_text='Menor = mais prioritário no fallback do leitor')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SourceHealth',
            fields=[
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='health', serialize=False, to='sources.source')),
                ('status', models.CharField(choices=[('UP', 'Operacional'), ('DEGRADED', 'Degradado'), ('DOWN', 'Fora do ar'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=16)),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('down_since', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('avg_latency_ms_5m', models.IntegerField(default=0)),
                ('p95_latency_ms_5m', models.IntegerField(default=0)),
                ('error_rate_5m', models.FloatField(default=0.0)),
                ('last_error_class', models.CharField(blank=True, default='', max_length=80)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('parser_drift_detected', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=200)),
                ('title_at_source', models.CharField(blank=True, default='', max_length=255)),
                ('cover_at_source', models.URLField(blank=True, default='', max_length=600)),
                ('language', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('url', models.URLField(blank=True, default='', max_length=600)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='employees.manga')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangas', to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='SourceChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=200)),
                ('number', models.DecimalField(decimal_places=2, max_digits=8)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('scanlator', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.URLField(blank=True, default='', max_length=600)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_chapters', to='sources.sourcemanga')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='SourceHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('origin', models.CharField(choices=[('probe', 'Probe ativo'), ('traffic', 'Tráfego real')], default='probe', max_length=16)),
                ('endpoint', models.CharField(help_text='search, manga, chapters, pages...', max_length=64)),
                ('success', models.BooleanField()),
                ('latency_ms', models.IntegerField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_class', models.CharField(blank=True, default='', max_length=80)),
                ('error_message', models.TextField(blank=True, default='')),
                ('extracted_count', models.IntegerField(blank=True, help_text='Número de itens parseados (para detectar parser drift em scrapers)', null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='sources.source')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['source', '-checked_at'], name='sources_sou_source__8e5217_idx'), models.Index(fields=['source', 'success', '-checked_at'], name='sources_sou_source__885fdc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sourcemanga',
            index=models.Index(fields=['source', 'language'], name='sources_sou_source__470c76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sourcemanga',
            unique_together={('source', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='sourcechapter',
            unique_together={('source_manga', 'external_id')},
        ),
    ]
