# Generated by Django 6.0 on 2026-01-02 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('alternative_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to='manga_covers/')),
                ('author', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ONGOING', 'Lançando'), ('COMPLETED', 'Finalizado'), ('HIATUS', 'Hiato')], default='ONGOING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(related_name='mangas', to='employees.category')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=1, max_digits=6)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='employees.manga')),
            ],
        ),
    ]
