# Generated by Django 6.0 on 2026-01-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_chapterimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['-number']},
        ),
        migrations.AddField(
            model_name='manga',
            name='mangadex_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='author',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
        migrations.AlterField(
            model_name='manga',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='mangas', to='employees.category'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='cover',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
