# Generated by Django 6.0 on 2026-01-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_chapter_options_manga_mangadex_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='mangadex_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
